# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Aditi Jain
title: Graduate Student at IIT Delhi
email: aditijain140102@gmail.com
website: aditija.in

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: aditijainx
github_username: AditiJain14
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: aditi-jain-3688231b6
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Google Scholar
    icon: fas fa-globe
    url: https://scholar.google.com/citations?user=sS2YRPAAAAAJ&hl=en
  # - title: another link
  #   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
  #   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a final year Master's student at IIT Delhi, studying Mathematics and Computing. I was also a visiting Research Assistant at Simon Fraser University, Burnaby, Canada in SFU NatLang Lab for the Spring and Summer 2023 terms.
  I was also a visiting intern in the 3DLG lab at SFU. I am interested in Multimodal NLP and Translation.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Graduate Research Assistant at NatLang Lab, SFU 
        link: https://github.com/AditiJain14/TIQTok
        sub_title: Supervised by Dr. Anoop Sarkar 
        caption: Dec 2022 - Aug 2023
        description: |
          **Simultaneous Machine Translation (Published in IWSLT Workshop @ ACL 2023)**
          
          SiMT models struggle to maintain translation quality while keeping latency low. In my work, we used an auxiliary language model to augment the training of the decoder model. Under this notion of target adaptive training, generating rare or difficult tokens is rewarded which improves the translation quality while reducing latency. The predictions made by a language model in the decoder are combined with the traditional cross entropy loss which frees up the focus on the source side context
          
      - layout: left
        title: Graduate Research Assistant at 3DLG Lab, SFU
        link: https://arxiv.org/pdf/2201.07366.pdf
        sub_title: Supervised by Dr. Angel Chang
        caption: May 2022 - July 2022
        description:
          sub_title: hello
          **TriCoLo Trimodal Contrastive Loss for Fine-grained Text to Shape Retrieval**
          
          Explored text augmentations such as word-dropout and switch-out for the TriCoLo model and used these to train the encoder with SimCSE method. Compared improvements in sentence embeddings by using pretrained models like BERT, GLoVe, and SentenceBERT.
      
      - layout: left
        title: Summer Undergraduate Research Intern at IIT Delhi
        link: https://www.vldb.org/pvldb/vol15/p1924-bhattacharya.pdf
        sub_title: Supervised by Dr. Srikanta Bedathur
        caption: May 2021 - Nov 2021
        description: |
          **Optimizing Bloom Filters with Learned Hashes**
          
          Replaced traditional hash functions with a random projection-based approach to exploit patterns in the data. Found upper bounds for size and false positive rate for the proposed method with extensive mathematical grounding. Awarded the Undergraduate Research Award for the project and laid the groundwork for a VLDB publication.
          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Indian Institute of Technology, Delhi
        caption: 2019 - 2024
        sub_title: Integrated Bachelor's and Master's of Technology in Mathematics and Computing
        description: | # this will include new lines to allow paragraphs
          During my undergrad, I studied introductory and advanced level courses of probability and statistics, linear algebra, calculus, game theory, optimization, data mining and data structures and algorithms.  I also took 2 electives of linguistics studying structure and function of word in language. 
           
          I was also an active member of the Literary Society at IIT Delhi.
        
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in NLP and maths, some of my other interests and hobbies are:
      - Reading (mostly fiction, you can check out my latest reads on my Goodreads)
      - Hiking (I like taking nature pictures!)
      - Obsessing over cats (to an unhealthy amount)

      Look at this cool image
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
