Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Aditi Jain
title: Graduate Student at IIT Delhi
email: aditijain140102@gmail.com
website: aditija.in

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: aditijainx
github_username: AditiJain14
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: aditi-jain-3688231b6
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Google Scholar
    icon: fas fa-globe
    url: https://scholar.google.com/citations?user=sS2YRPAAAAAJ&hl=en
  # - title: another link
  #   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
  #   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a final year Master's student at IIT Delhi, studying Mathematics and Computing. Born in Pune, Maharasthra and I have now shifted to St. John's, Newfoundland, Canada. I am fluent in English, Hindi and Marathi. <br>
  I was a Research Assistant at Simon Fraser University, Burnaby, Canada in <a href="http://natlang.cs.sfu.ca/">NatLang Lab</a> for the Spring and Summer 2023 terms where I worked with Prof. Anoop Sarkar on Simultaneous Machine Translation. 
  I was also a visiting research intern in the <a href="https://angelxuanchang.github.io/group.html">3DLG Lab</a> at SFU. 

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Simultaneous Machine Translation (Published in IWSLT Workshop @ ACL 2023)
        sub_title: Graduate Research Assistant at NatLang Lab, SFU 
        link: https://github.com/AditiJain14/TIQTok
        caption: Supervised by Dr. Anoop Sarkar (Dec 2022 - Aug 2023)
        description: |
          SiMT models struggle to maintain translation quality while keeping latency low. In my work, we used an auxiliary language model to augment the training of the decoder model. Under this notion of target adaptive training, generating rare or difficult tokens is rewarded which improves the translation quality while reducing latency. The predictions made by a language model in the decoder are combined with the traditional cross entropy loss which frees up the focus on the source side context. This training method significantly improved BLEU scores in the English-Vietnamese and English-German language pairs, especially in the early latencies which are more difficult to translate for.
          
      - layout: top-middle
        title: TriCoLo - Trimodal Contrastive Loss for Text to 3D Shape Retrieval 
        sub_title: Graduate Research Assistant at 3DLG Lab, SFU
        link: https://arxiv.org/pdf/2201.07366.pdf
        caption: Supervised by Dr. Angel Chang (May 2022 - July 2022)
        description: |
          The text, image and voxels of the objects of the Text2Shape dataset are embedded in a common space using a trimodality contrastive loss. I experimented with introducing different augmentations to the text and image encoding modules, and implemented methods like SimCSE on sentence embeddings with augmentations such as word-dropout and switch-out. Compared improvements in sentence embeddings by using pretrained models like BERT, GLoVe, and SentenceBERT.
      
      - layout: top-middle
        title: Optimizing Bloom Filters with Learned Hashes 
        sub_title: Summer Undergraduate Research Intern at IIT Delhi
        link: https://dl.acm.org/doi/10.14778/3538598.3538613
        caption: Supervised by Dr. Srikanta Bedathur (May 2021 - Nov 2021)
        description: |
          Replaced traditional hash functions with a random projection-based approach to exploit patterns in the data by projecting each data point onto a set of vectors. The vectors themselves were divided into bins (to map to indices of the bit array) and the best vector set for a particular dataset was selected after some iterations. This method showed a significant reduction in the memory footprint of a BF while maintaining the desired false positive rate (FPR). I also found upper bounds for size and FPR for the proposed method with extensive mathematical grounding. Awarded the Undergraduate Research Award for the project and laid the groundwork for a VLDB publication.
  
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        description: |
          **Language Model Based Target Token Importance Rescaling for Simultaneous Neural Machine Translation** <br>
          Aditi Jain, Nishant Kambhatla, Anoop Sarkar, Association for Computational Linguistics (ACL) International Conference on Spoken Language Translation (IWSLT) Workshop 2023. <a href="https://aclanthology.org/2023.iwslt-1.32/"> [DOI] </a>

  - title: Projects
    layout: list
    content:
      - layout: left                      # other value (or no value) means no border will be displayed
        title: 
        link: 
        caption: Supervised by Dr. JayaShree Kalpathy-Cramer, Harvard University (Aug 2022 - Nov 2022)
        description: | # this will include new lines to allow paragraphs
          **Analysis of Breast Histopathology Images** <br>
          + I worked on segmentation and classification of whole slide images of breast cancer patients to analyse the effect of spatial distribution and the count of immune cells and predict breast cancer subtypes and treatment outcomes. I also generated heatmaps to add clinical interpretability to the attention-based model (such as the CLAM model).
      
      - layout: left
        # title: Improving Robustness of Visual Question Answering (VQA) Systems
        title : 
        link: https://doi.org/10.1007/978-3-030-68790-8_28
        caption: Supervised by Dr. Ashish Anand, IIT Guwahati (May 2020 - Jul 2020)
        description: | # this will include new lines to allow paragraphs
          **Improving Robustness of Visual Question Answering (VQA) Systems** <br>
          + I helped annotate a new VQA dataset with 3 categorical rephrasings (30k questions) and contributed to an ICPRW paper. I also trained character-level & word-level encoder decoder models for rephrasing generation using RNNs. I also experimented with using pretrained DistilBert model and a Gensim embedding layer to improve consistency by 15%.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Indian Institute of Technology, Delhi
        caption: 2019 - 2024
        sub_title: Integrated Bachelor's and Master's | Mathematics and Computing
        description: | # this will include new lines to allow paragraphs
          During my undergrad, I studied introductory and advanced level courses of probability and statistics, linear algebra, calculus, game theory, optimization, data mining and data structures and algorithms.  I also took 2 electives of linguistics studying structure and function of word in language. 
           
          I was also an active member of the Literary Society at IIT Delhi.
        
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in NLP and maths, some of my other interests and hobbies are:
      - Reading (mostly fiction, you can check out my latest reads on my Goodreads)
      - Hiking (I like taking nature pictures!)
      - Obsessing over cats (to an unhealthy amount)
      ![Trees](/modern-resume-theme/images/cat1.jpg "Athena")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
